Script started on Sun 10 Aug 2014 10:26:06 AM PDT
~
bamor002@well $ cd cs100/rshell/
~/cs100/rshell
bamor002@well $ make
g++ -c -Wall -Werror -ansi -pedantic src/main.cpp
mkdir bin
g++ main.o -o ./bin/rshell
~/cs100/rshell
bamor002@well $ bin.r[K[K/rshell 
bamor002@well.cs.ucr.edu$ ls -l
total 32
drwx------ 2 bamor002 classes 4096 Aug 10 10:26 bin
-rw------- 1 bamor002 classes    0 Aug 10 10:26 exec.script
-rw------- 1 bamor002 classes 1483 Aug 10 08:54 LICENSE
-rw------- 1 bamor002 classes 5184 Aug 10 10:26 main.o
-rw------- 1 bamor002 classes  145 Aug 10 08:54 Makefile
-rw------- 1 bamor002 classes  965 Aug 10 08:54 README.md
drwx------ 2 bamor002 classes 4096 Aug 10 10:25 src
drwx------ 2 bamor002 classes 4096 Aug 10 08:54 tests
bamor002@well.cs.ucr.edu$ ls #-la
bin  exec.script  LICENSE  main.o  Makefile  README.md	src  tests
bamor002@well.cs.ucr.edu$ #tsting comments^[[D                  esting commm ents
bamor002@well.cs.ucr.edu$ 
bamor002@well.cs.ucr.edu$                ls        -l #test spaces between commands
total 32
drwx------ 2 bamor002 classes 4096 Aug 10 10:26 bin
-rw------- 1 bamor002 classes    0 Aug 10 10:26 exec.script
-rw------- 1 bamor002 classes 1483 Aug 10 08:54 LICENSE
-rw------- 1 bamor002 classes 5184 Aug 10 10:26 main.o
-rw------- 1 bamor002 classes  145 Aug 10 08:54 Makefile
-rw------- 1 bamor002 classes  965 Aug 10 08:54 README.md
drwx------ 2 bamor002 classes 4096 Aug 10 10:25 src
drwx------ 2 bamor002 classes 4096 Aug 10 08:54 tests
bamor002@well.cs.ucr.edu$ mkdir newFolder
bamor002@well.cs.ucr.edu$ ls #verify the new folder
bin  exec.script  LICENSE  main.o  Makefile  newFolder	README.md  src	tests
bamor002@well.cs.ucr.edu$ touch newFile
bamor002@well.cs.ucr.edu$ ls
bin	     LICENSE  Makefile	newFolder  src
exec.script  main.o   newFile	README.md  tests
bamor002@well.cs.ucr.edu$ ps
  PID TTY          TIME CMD
18741 pts/18   00:00:00 bash
18753 pts/18   00:00:00 rshell
18778 pts/18   00:00:00 ps
bamor002@well.cs.ucr.edu$ firefox &
bamor002@well.cs.ucr.edu$ ps
  PID TTY          TIME CMD
18741 pts/18   00:00:00 bash
18753 pts/18   00:00:00 rshell
18782 pts/18   00:00:00 firefox
18792 pts/18   00:00:00 firefox
18793 pts/18   00:00:00 ps
bamor002@well.cs.ucr.edu$ Error: cannot open display: :0

bamor002@well.cs.ucr.edu$ #test open          geany &         &    #test with spaces 
bamor002@well.cs.ucr.edu$ ps
bamor002@well.cs.ucr.edu$   PID TTY          TIME CMD
18741 pts/18   00:00:00 bash
18753 pts/18   00:00:00 rshell
18819 pts/18   00:00:00 geany
18820 pts/18   00:00:00 ps

bamor002@well.cs.ucr.edu$ Geany: cannot open display


bamor002@well.cs.ucr.edu$ exit
~/cs100/rshell
bamor002@well $ exit
exit

Script done on Sun 10 Aug 2014 10:31:16 AM PDT
